### PR TITLE
Makefile

### PR DESCRIPTION
**Pull request by jc00ke**
I was curious if you'd merge a Makefile? I've needed to install this project on many servers and not having an easy way to install/uninstall ended up taking a lot of time over time.

I poached the Makefile from [ruby-install](https://github.com/postmodern/ruby-install/blob/master/Makefile) which is pretty solid.

Thanks!

### CODE REVIEW

**Comment by jc00ke** [comment]
@perusio ping

**Comment by perusio** [comment]
Hallo,

I think it's a good idea. I just need to update the stuff in building my debian package so that I skip the makefile since there `dh_install` handles the things. We need to add something to the README in that case. Stating that you can install the script via the Makefile.

**Comment by perusio** [comment]
Thanks a lot.

**Comment by jc00ke** [comment]
Thank you @perusio!

**Pull request merged**
